title: Ioannis Diamantidis
email: diamantidis@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog to publish my ideas and thoughts about software developer
baseurl: ""
url: "https://diamantidis.github.io"
permalink: /:categories/:year/:month/:day/:title

# Logo & images
logo: /assets/socialIcon.png
defaults:
  - scope:
      path: ""
    values:
      image: /assets/socialIcon.png

# Author
author:
  name: Ioannis Diamantidis
  url: https://diamantidis.github.io
  email: diamantidis@outlook.com
  twitter: diamantidis_io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

sass:
  sass_dir: _scss
  style: :compressed

footer-links:
  rss: rss
  twitter: diamantidis_io
  github: diamantidis
  email: diamantidis@outlook.com
  # facebook:
  linkedin: ioannis-diamantidis

# Exclude from processing.
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - Dangerfile

# Google Analytics
google_analytics: UA-121787430-1

# Disqus
# disqus:
#   shortname: ioannisblog-1

social:
  - name: Twitter
    icon: twitter
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    desc: Friend me on Facebook
    share: true

  - name: LinkedIn
    icon: linkedin
    desc: Connect with me on LinkedIn
    share: true

# Pagination
paginate: 7
paginate_path: /page/:num/

twitter:
  username: diamantidis_io
  card: summary

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []